<?php

use Drupal\cp22_saulnier_edito\Manager\EditoManager;

/**
 * Implements hook_preprocess_HOOK().
 */
//function cp22_saulnier_edito_preprocess_node(&$variables) {
//
//  /** @var \Drupal\node\Entity\Node $node */
//
//  //On check seulement les nodes
//  $node = $variables['node'];
//
//  if ($node->bundle() == EditoManager::EDITO_LIST_BUNDLE){
//
//    /** @var \Drupal\cp22_saulnier_edito\Manager\EditoManager $editoManager */
//    $editoManager = Drupal::service(EditoManager::class);
//
//  }
//}






