<?php

use Drupal\node\NodeInterface;
//use Drupal\cp22_saulnier_news\Plugin\QueueWorker;
/**
 * Implements hook_preprocess_HOOK().
 */
function cp22_saulnier_socials_preprocess_node(&$variables) {
//
//  /** @var \Drupal\node\Entity\Node $node */
//
//  //On check seulement les nodes
//  $node = $variables['node'];
//
//  if ($node->bundle() == NewsManager::NEWS_LIST_BUNDLE){
//
//    /** @var \Drupal\cp22_saulnier_news\Manager\NewsManager $newsManager */
//    //On charge la class NewswManager et on la stock dans une variable
//    $newsManager = Drupal::service(NewsManager::class);
//
////    $variables = $newsManager->addNewsListToNodePreprocessVariableIfNeeded($variables);
//
//    //News List filtered
//    //Récupère la variable d'URL stté dans le submitForm
//    $themeId = \Drupal::requestStack()->getCurrentRequest()->get('theme');
//    $dateSort = Drupal::requestStack()->getCurrentRequest()->get('date-sort');
//
//    //Condition évitable en faisant évoluer la methode getBuiltNewsNodeForNewsListPage dans le manager en lui ajoutant un param facultatif.
//    if ($themeId){
//      $variables[NewsManager::NEWS_LIST_PREPROCESS_KEY] = $newsManager->getBuiltNewsNodeForNewsListPageByThemeId($themeId, $dateSort);
//    }
//    else{
//      //On récupère seulement les nodes de type NEW_LIST_PREPROCESS_KEY (cad newslist) donné par $newsmanager
//      $variables[NewsManager::NEWS_LIST_PREPROCESS_KEY] = $newsManager->getBuiltNewsNodeForNewsListPage($dateSort);
//    }
//
//    //Création du formulaire
////       $form = Drupal::formBuilder()->getForm('Drupal\cp22_saulnier_news\Form\NewsListForm');
////       $variables['form'] = $form;
//
//     $variables['pager'] = ['#type'=>'pager'];
//  }

//  $data = [
//    'modélisme',
//    'jeux vidéos',
//  ];
//  $queue = Drupal::queue('cp22_saulnier_news_insertnewsworker');
//  $queue->createQueue();
//  foreach($data as $theme) {
//    $queue->createItem($theme);
//  }
}

///**
// * Implements hook_form_alter().
// */
//function cp22_saulnier_news_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//  if ($form_id = 'news_list_form'){
//    $form['theme']['#title'] = t('Super theme');
//    $form['#validate'][] = 'mon_validate';
//  }
//}
//
//function mon_validate(&$form, \Drupal\Core\Form\FormStateInterface $formState){
//  $formState->setErrorByName('theme','Bof');
//}





